#!/usr/bin/env ts-node

/**
 * Script de migration vers Firebase
 * Ce script initialise Firebase et migre les données par défaut vers Firestore
 */

import { FirebaseApp, initializeApp } from "firebase/app";
import { Auth, getAuth, signInAnonymously } from "firebase/auth";
import {
  Firestore,
  collection,
  doc,
  getFirestore,
  serverTimestamp,
  setDoc,
  writeBatch,
} from "firebase/firestore";

// Types
interface DiceFace {
  label: string;
  category: "payer" | "repas" | "activite";
  emoji: string;
  weight: number;
  actions?: string[];
  isDefault: boolean;
  isActive: boolean;
}

interface ConfigDefaults {
  FREE_ROLLS_PER_DAY: number;
  LIFETIME_PRICE: string;
  PAYWALL_TITLE: string;
  PAYWALL_BULLETS: string;
  FEATURE_FLAGS: {
    customFaces: boolean;
    history: boolean;
    analytics: boolean;
    sharing: boolean;
  };
}

interface FirebaseContext {
  app: FirebaseApp;
  db: Firestore;
  auth: Auth;
}

// Configuration Firebase
const firebaseConfig = {
  apiKey: "AIzaSyAXrDxGHxOgHcFxRfHEL2Qi82KpE29CJMY",
  authDomain: "love-dice-7a878.firebaseapp.com",
  projectId: "love-dice-7a878",
  storageBucket: "love-dice-7a878.firebasestorage.app",
  messagingSenderId: "916106041141",
  appId: "1:916106041141:web:a41b259be98ae885cd9e7c",
  measurementId: "G-7Z5GB9RCT5",
};

const DEFAULT_FACES: DiceFace[] = [
  // ==================== CATÉGORIE PAYER (100 faces) ====================
  // Basiques
  {
    label: "Tu paies",
    category: "payer",
    emoji: "🍷",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Je paie",
    category: "payer",
    emoji: "💳",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "50/50",
    category: "payer",
    emoji: "🧾",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pile ou Face",
    category: "payer",
    emoji: "🪙",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pierre-Papier-Ciseaux",
    category: "payer",
    emoji: "✂️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Le plus jeune paie",
    category: "payer",
    emoji: "👶",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Le plus âgé paie",
    category: "payer",
    emoji: "👴",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a eu l'idée paie",
    category: "payer",
    emoji: "💡",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Le plus grand paie",
    category: "payer",
    emoji: "📏",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Le plus petit paie",
    category: "payer",
    emoji: "🤏",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui rit en premier paie",
    category: "payer",
    emoji: "😂",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a le plus de cash",
    category: "payer",
    emoji: "💰",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Tirage au dé (1-3 vs 4-6)",
    category: "payer",
    emoji: "🎲",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Bataille de pouces",
    category: "payer",
    emoji: "👍",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Premier à dire 'banane'",
    category: "payer",
    emoji: "🍌",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Dernier arrivé paie",
    category: "payer",
    emoji: "🏃‍♂️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a parlé en dernier",
    category: "payer",
    emoji: "🤐",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui porte du rouge",
    category: "payer",
    emoji: "🔴",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui porte du bleu",
    category: "payer",
    emoji: "🔵",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Le plus de 'likes' Instagram",
    category: "payer",
    emoji: "❤️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui né en premier dans l'année",
    category: "payer",
    emoji: "🎂",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui né le plus tard",
    category: "payer",
    emoji: "🍰",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Si l'heure est paire, tu paies",
    category: "payer",
    emoji: "⏰",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui s'est levé en premier",
    category: "payer",
    emoji: "🌅",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui s'est couché le plus tard",
    category: "payer",
    emoji: "🌙",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Paiement Carte Bleue",
    category: "payer",
    emoji: "💳",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Paiement Cash uniquement",
    category: "payer",
    emoji: "💵",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Paiement mobile",
    category: "payer",
    emoji: "📱",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Venmo/PayPal",
    category: "payer",
    emoji: "💸",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Chèques restaurant",
    category: "payer",
    emoji: "🎫",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "70/30 en ta faveur",
    category: "payer",
    emoji: "📊",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "30/70 en ma faveur",
    category: "payer",
    emoji: "📈",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Chacun paie ce qu'il commande",
    category: "payer",
    emoji: "🧮",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pourboire x2 pour le perdant",
    category: "payer",
    emoji: "💰",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Addition + dessert gratuit",
    category: "payer",
    emoji: "🍰",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Bras de fer décide",
    category: "payer",
    emoji: "💪",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Quiz culture générale",
    category: "payer",
    emoji: "🧠",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui tient le plus longtemps sur un pied",
    category: "payer",
    emoji: "🦶",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pierre-feuille-ciseaux-lézard-Spock",
    category: "payer",
    emoji: "🖖",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Bataille de regards",
    category: "payer",
    emoji: "👁️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Chi-fou-mi version coréenne",
    category: "payer",
    emoji: "🥢",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui éternue en premier",
    category: "payer",
    emoji: "🤧",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a le plus d'applications",
    category: "payer",
    emoji: "📱",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a le moins de batterie",
    category: "payer",
    emoji: "🔋",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui connaît le plus de mots de passe",
    category: "payer",
    emoji: "🔐",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Le plus de notifications non lues",
    category: "payer",
    emoji: "🔔",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a bu le plus d'eau aujourd'hui",
    category: "payer",
    emoji: "💧",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a fait le plus de pas",
    category: "payer",
    emoji: "👣",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a pris le plus de photos",
    category: "payer",
    emoji: "📸",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a envoyé le plus de messages",
    category: "payer",
    emoji: "💬",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a écouté le plus de musique",
    category: "payer",
    emoji: "🎵",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a regardé le plus de vidéos",
    category: "payer",
    emoji: "🎬",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui utilise le plus les réseaux sociaux",
    category: "payer",
    emoji: "📲",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a le plus d'amis Facebook",
    category: "payer",
    emoji: "👥",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a le plus de followers Instagram",
    category: "payer",
    emoji: "📷",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a le plus de matches Tinder",
    category: "payer",
    emoji: "💕",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui connaît le plus de langues",
    category: "payer",
    emoji: "🌍",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a visité le plus de pays",
    category: "payer",
    emoji: "✈️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a le plus de tatouages",
    category: "payer",
    emoji: "🎨",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a le plus de piercings",
    category: "payer",
    emoji: "💎",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a les cheveux les plus longs",
    category: "payer",
    emoji: "💇‍♀️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a les cheveux les plus courts",
    category: "payer",
    emoji: "💇‍♂️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui porte le plus de bijoux",
    category: "payer",
    emoji: "💍",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a les plus grands pieds",
    category: "payer",
    emoji: "👟",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a les plus petites mains",
    category: "payer",
    emoji: "🤲",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a les yeux les plus clairs",
    category: "payer",
    emoji: "👀",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui sourit le plus souvent",
    category: "payer",
    emoji: "😊",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui cligne des yeux en premier",
    category: "payer",
    emoji: "😉",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a la voix la plus grave",
    category: "payer",
    emoji: "🎤",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a la voix la plus aiguë",
    category: "payer",
    emoji: "🎵",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui parle le plus fort",
    category: "payer",
    emoji: "📢",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui murmure le mieux",
    category: "payer",
    emoji: "🤫",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui imite le mieux les animaux",
    category: "payer",
    emoji: "🐸",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui fait le meilleur accent",
    category: "payer",
    emoji: "🗣️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui raconte la meilleure blague",
    category: "payer",
    emoji: "🤡",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui danse le mieux",
    category: "payer",
    emoji: "💃",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui chante le mieux",
    category: "payer",
    emoji: "🎤",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui dessine le mieux",
    category: "payer",
    emoji: "🎨",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui cuisine le mieux",
    category: "payer",
    emoji: "👨‍🍳",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui conduit le mieux",
    category: "payer",
    emoji: "🚗",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui nage le mieux",
    category: "payer",
    emoji: "🏊‍♂️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui court le plus vite",
    category: "payer",
    emoji: "🏃‍♂️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui saute le plus haut",
    category: "payer",
    emoji: "🦘",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui fait le plus de pompes",
    category: "payer",
    emoji: "💪",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui tient le plus longtemps en planche",
    category: "payer",
    emoji: "🧘‍♂️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui est le plus flexible",
    category: "payer",
    emoji: "🤸‍♀️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a la meilleure mémoire",
    category: "payer",
    emoji: "🧠",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui résout le plus vite un Rubik's cube",
    category: "payer",
    emoji: "🧩",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui compte le plus vite jusqu'à 100",
    category: "payer",
    emoji: "🔢",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui dit l'alphabet à l'envers le plus vite",
    category: "payer",
    emoji: "🔤",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui se souvient de plus de numéros de téléphone",
    category: "payer",
    emoji: "☎️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui connaît le plus de capitales",
    category: "payer",
    emoji: "🌏",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui nomme le plus d'animaux en 30 secondes",
    category: "payer",
    emoji: "🦁",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui récite le plus de paroles de chanson",
    category: "payer",
    emoji: "🎶",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui connaît le plus de films",
    category: "payer",
    emoji: "🎬",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a lu le plus de livres",
    category: "payer",
    emoji: "📚",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui connaît le plus de recettes",
    category: "payer",
    emoji: "📝",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a le plus voyagé",
    category: "payer",
    emoji: "🧳",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui parle le plus de langues",
    category: "payer",
    emoji: "🗣️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a le plus d'hobbies",
    category: "payer",
    emoji: "🎭",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui collectionne le plus de choses",
    category: "payer",
    emoji: "🏆",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Celui qui a gagné le plus de concours",
    category: "payer",
    emoji: "🥇",
    weight: 1,
    isDefault: true,
    isActive: true,
  },

  // ==================== CATÉGORIE REPAS (100 faces) ====================
  {
    label: "Restaurant",
    category: "repas",
    emoji: "🍽️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Livraison",
    category: "repas",
    emoji: "🍕",
    weight: 1,
    actions: ["delivery"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Street food",
    category: "repas",
    emoji: "🌮",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Fait maison",
    category: "repas",
    emoji: "🍝",
    weight: 1,
    actions: ["recipe"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Surprise de l'autre",
    category: "repas",
    emoji: "🎁",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Sushi",
    category: "repas",
    emoji: "🍣",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Burger gourmet",
    category: "repas",
    emoji: "🍔",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine italienne",
    category: "repas",
    emoji: "🇮🇹",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine française",
    category: "repas",
    emoji: "🇫🇷",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine asiatique",
    category: "repas",
    emoji: "🥢",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine mexicaine",
    category: "repas",
    emoji: "🌶️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine indienne",
    category: "repas",
    emoji: "🍛",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine libanaise",
    category: "repas",
    emoji: "🥙",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine grecque",
    category: "repas",
    emoji: "🇬🇷",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine espagnole",
    category: "repas",
    emoji: "🥘",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine thaïlandaise",
    category: "repas",
    emoji: "🍜",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine coréenne",
    category: "repas",
    emoji: "🥟",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine chinoise",
    category: "repas",
    emoji: "🥠",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine vietnamienne",
    category: "repas",
    emoji: "🍲",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine américaine",
    category: "repas",
    emoji: "🇺🇸",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Food truck",
    category: "repas",
    emoji: "🚚",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pâtisserie",
    category: "repas",
    emoji: "🧁",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Marché local",
    category: "repas",
    emoji: "🥕",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Café cosy",
    category: "repas",
    emoji: "☕",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Brunch",
    category: "repas",
    emoji: "🥞",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Petit-déjeuner tardif",
    category: "repas",
    emoji: "🥐",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Déjeuner d'affaires",
    category: "repas",
    emoji: "💼",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Dîner romantique",
    category: "repas",
    emoji: "💕",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Apéritif dinatoire",
    category: "repas",
    emoji: "🍷",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Barbecue",
    category: "repas",
    emoji: "🔥",
    weight: 1,
    actions: ["weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pique-nique",
    category: "repas",
    emoji: "🧺",
    weight: 1,
    actions: ["weather", "maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant étoilé",
    category: "repas",
    emoji: "⭐",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Bistrot de quartier",
    category: "repas",
    emoji: "🏪",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Brasserie",
    category: "repas",
    emoji: "🍺",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Wine bar",
    category: "repas",
    emoji: "🍾",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Bar à tapas",
    category: "repas",
    emoji: "🍤",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Rooftop restaurant",
    category: "repas",
    emoji: "🏙️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant avec vue",
    category: "repas",
    emoji: "🌅",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant en bord de mer",
    category: "repas",
    emoji: "🌊",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Auberge de campagne",
    category: "repas",
    emoji: "🏞️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant de montagne",
    category: "repas",
    emoji: "⛰️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine fusion",
    category: "repas",
    emoji: "🌍",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine végétarienne",
    category: "repas",
    emoji: "🥗",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine végane",
    category: "repas",
    emoji: "🌱",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant bio",
    category: "repas",
    emoji: "🌿",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine sans gluten",
    category: "repas",
    emoji: "🌾",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine halal",
    category: "repas",
    emoji: "🕌",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine kasher",
    category: "repas",
    emoji: "✡️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Buffet à volonté",
    category: "repas",
    emoji: "🍴",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Menu dégustation",
    category: "repas",
    emoji: "👨‍🍳",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine moléculaire",
    category: "repas",
    emoji: "⚗️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Street art culinaire",
    category: "repas",
    emoji: "🎨",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant thématique",
    category: "repas",
    emoji: "🎭",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Dîner-spectacle",
    category: "repas",
    emoji: "🎪",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant de poissons",
    category: "repas",
    emoji: "🐟",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Steakhouse",
    category: "repas",
    emoji: "🥩",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pizzeria artisanale",
    category: "repas",
    emoji: "🍕",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Crêperie",
    category: "repas",
    emoji: "🥞",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Boulangerie-pâtisserie",
    category: "repas",
    emoji: "🥖",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Glacier artisanal",
    category: "repas",
    emoji: "🍦",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Chocolaterie",
    category: "repas",
    emoji: "🍫",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Salon de thé",
    category: "repas",
    emoji: "🍵",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Coffee shop",
    category: "repas",
    emoji: "☕",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Brûlerie de café",
    category: "repas",
    emoji: "☕",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Bar à jus",
    category: "repas",
    emoji: "🥤",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Smoothie bar",
    category: "repas",
    emoji: "🍹",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Bubble tea",
    category: "repas",
    emoji: "🧋",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant tournant",
    category: "repas",
    emoji: "🎡",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant dans le noir",
    category: "repas",
    emoji: "🕯️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant sur l'eau",
    category: "repas",
    emoji: "⛵",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant dans un train",
    category: "repas",
    emoji: "🚂",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant dans un château",
    category: "repas",
    emoji: "🏰",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant dans une grotte",
    category: "repas",
    emoji: "🕳️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant dans un arbre",
    category: "repas",
    emoji: "🌳",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant sous-marin",
    category: "repas",
    emoji: "🐠",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant dans les nuages",
    category: "repas",
    emoji: "☁️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pop-up restaurant",
    category: "repas",
    emoji: "⏰",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Restaurant éphémère",
    category: "repas",
    emoji: "🎪",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine de rue internationale",
    category: "repas",
    emoji: "🌍",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Marché de nuit",
    category: "repas",
    emoji: "🌃",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Festival gastronomique",
    category: "repas",
    emoji: "🎉",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cours de cuisine",
    category: "repas",
    emoji: "👨‍🍳",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Atelier pâtisserie",
    category: "repas",
    emoji: "🧁",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Dégustation de vins",
    category: "repas",
    emoji: "🍷",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Dégustation de fromages",
    category: "repas",
    emoji: "🧀",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Dégustation de chocolats",
    category: "repas",
    emoji: "🍫",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Dégustation d'huîtres",
    category: "repas",
    emoji: "🦪",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Dégustation de caviar",
    category: "repas",
    emoji: "🥄",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Brunch du dimanche",
    category: "repas",
    emoji: "☀️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Petit-déjeuner au lit",
    category: "repas",
    emoji: "🛏️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Dîner aux chandelles",
    category: "repas",
    emoji: "🕯️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Repas sur la terrasse",
    category: "repas",
    emoji: "🌿",
    weight: 1,
    actions: ["weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pique-nique au coucher du soleil",
    category: "repas",
    emoji: "🌅",
    weight: 1,
    actions: ["weather", "maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Repas de minuit",
    category: "repas",
    emoji: "🌙",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Petit-déjeuner de champion",
    category: "repas",
    emoji: "🏆",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Déjeuner sur l'herbe",
    category: "repas",
    emoji: "🌱",
    weight: 1,
    actions: ["weather", "maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Goûter d'enfance",
    category: "repas",
    emoji: "🧒",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Repas nostalgique",
    category: "repas",
    emoji: "💭",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine de grand-mère",
    category: "repas",
    emoji: "👵",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Plat réconfortant",
    category: "repas",
    emoji: "🤗",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cuisine du monde entier en une soirée",
    category: "repas",
    emoji: "🌍",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },

  // ==================== CATÉGORIE ACTIVITÉ (100 faces) ====================
  {
    label: "Cinéma maison",
    category: "activite",
    emoji: "🎬",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Jeu de société",
    category: "activite",
    emoji: "🎲",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Balade nocturne",
    category: "activite",
    emoji: "🌙",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Tenue chic",
    category: "activite",
    emoji: "👔",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Budget max 30€",
    category: "activite",
    emoji: "💶",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Dessert obligatoire",
    category: "activite",
    emoji: "🍰",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pas d'écran",
    category: "activite",
    emoji: "📵",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Karaoké",
    category: "activite",
    emoji: "🎤",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Musée",
    category: "activite",
    emoji: "🖼️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Bowling",
    category: "activite",
    emoji: "🎳",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Mini-golf",
    category: "activite",
    emoji: "⛳",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Parc d'attractions",
    category: "activite",
    emoji: "🎢",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Zoo/Aquarium",
    category: "activite",
    emoji: "🐧",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Randonnée",
    category: "activite",
    emoji: "🥾",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Théâtre",
    category: "activite",
    emoji: "🎭",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Galerie d'art",
    category: "activite",
    emoji: "🖼️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Concert live",
    category: "activite",
    emoji: "🎸",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Arcade",
    category: "activite",
    emoji: "🕹️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Plage/Lac",
    category: "activite",
    emoji: "🏖️",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Spa/Massage",
    category: "activite",
    emoji: "💆‍♀️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cours de danse",
    category: "activite",
    emoji: "💃",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Match sportif",
    category: "activite",
    emoji: "⚽",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Shopping",
    category: "activite",
    emoji: "🛍️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Bibliothèque",
    category: "activite",
    emoji: "📚",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Marché aux puces",
    category: "activite",
    emoji: "🏺",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Escape room",
    category: "activite",
    emoji: "🔐",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Laser tag",
    category: "activite",
    emoji: "🔫",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Paintball",
    category: "activite",
    emoji: "🎨",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Accrobranche",
    category: "activite",
    emoji: "🌳",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Piscine",
    category: "activite",
    emoji: "🏊‍♂️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Patinoire",
    category: "activite",
    emoji: "⛸️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Ski/Snowboard",
    category: "activite",
    emoji: "⛷️",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "VTT",
    category: "activite",
    emoji: "🚵‍♂️",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Course à pied",
    category: "activite",
    emoji: "🏃‍♀️",
    weight: 1,
    actions: ["weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Yoga en extérieur",
    category: "activite",
    emoji: "🧘‍♀️",
    weight: 1,
    actions: ["weather", "maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Méditation",
    category: "activite",
    emoji: "🕉️",
    weight: 1,
    isDefault: true,
    isActive: true,
  },
  {
    label: "Séance photo",
    category: "activite",
    emoji: "📸",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Chasse aux trésors",
    category: "activite",
    emoji: "🗺️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Geocaching",
    category: "activite",
    emoji: "📍",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Observation des étoiles",
    category: "activite",
    emoji: "🌟",
    weight: 1,
    actions: ["weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Coucher de soleil",
    category: "activite",
    emoji: "🌅",
    weight: 1,
    actions: ["weather", "maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Lever de soleil",
    category: "activite",
    emoji: "🌄",
    weight: 1,
    actions: ["weather", "maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Festival de musique",
    category: "activite",
    emoji: "🎪",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Foire",
    category: "activite",
    emoji: "🎡",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Marché de Noël",
    category: "activite",
    emoji: "🎄",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Feu de camp",
    category: "activite",
    emoji: "🔥",
    weight: 1,
    actions: ["weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Planétarium",
    category: "activite",
    emoji: "🪐",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Aquarium",
    category: "activite",
    emoji: "🐠",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Jardin botanique",
    category: "activite",
    emoji: "🌸",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Parc naturel",
    category: "activite",
    emoji: "🍃",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Ferme pédagogique",
    category: "activite",
    emoji: "🐄",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Visite de château",
    category: "activite",
    emoji: "🏰",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cathédrale/Église",
    category: "activite",
    emoji: "⛪",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Site archéologique",
    category: "activite",
    emoji: "🏛️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Monument historique",
    category: "activite",
    emoji: "🗿",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Tour guidée",
    category: "activite",
    emoji: "🎯",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Visite en bus touristique",
    category: "activite",
    emoji: "🚌",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Croisière",
    category: "activite",
    emoji: "🛳️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Balade en bateau",
    category: "activite",
    emoji: "⛵",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Kayak",
    category: "activite",
    emoji: "🛶",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Stand up paddle",
    category: "activite",
    emoji: "🏄‍♂️",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Plongée sous-marine",
    category: "activite",
    emoji: "🤿",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Snorkeling",
    category: "activite",
    emoji: "🐠",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Pêche",
    category: "activite",
    emoji: "🎣",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Équitation",
    category: "activite",
    emoji: "🐎",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Go-kart",
    category: "activite",
    emoji: "🏎️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Karting",
    category: "activite",
    emoji: "🏁",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Circuit automobile",
    category: "activite",
    emoji: "🏆",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Simulateur de vol",
    category: "activite",
    emoji: "✈️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Parachute",
    category: "activite",
    emoji: "🪂",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Saut à l'élastique",
    category: "activite",
    emoji: "🤸‍♂️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Vol en montgolfière",
    category: "activite",
    emoji: "🎈",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Vol en hélicoptère",
    category: "activite",
    emoji: "🚁",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Trampoline park",
    category: "activite",
    emoji: "🤸‍♀️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Escalade",
    category: "activite",
    emoji: "🧗‍♀️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Via ferrata",
    category: "activite",
    emoji: "⛰️",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Spéléologie",
    category: "activite",
    emoji: "🕳️",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Canyoning",
    category: "activite",
    emoji: "💦",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Rafting",
    category: "activite",
    emoji: "🚣‍♀️",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Surf",
    category: "activite",
    emoji: "🏄‍♀️",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Windsurf",
    category: "activite",
    emoji: "🏄‍♂️",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Kitesurf",
    category: "activite",
    emoji: "🪁",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Parapente",
    category: "activite",
    emoji: "🪂",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Delta plane",
    category: "activite",
    emoji: "🪂",
    weight: 1,
    actions: ["maps", "weather"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Course d'orientation",
    category: "activite",
    emoji: "🧭",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Paintball",
    category: "activite",
    emoji: "🎨",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Airsoft",
    category: "activite",
    emoji: "🔫",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Tir à l'arc",
    category: "activite",
    emoji: "🏹",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Stand de tir",
    category: "activite",
    emoji: "🎯",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Casino",
    category: "activite",
    emoji: "🎰",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Bar lounge",
    category: "activite",
    emoji: "🍸",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Boîte de nuit",
    category: "activite",
    emoji: "💃",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Club privé",
    category: "activite",
    emoji: "🥂",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Soirée à thème",
    category: "activite",
    emoji: "🎭",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Spectacle de magie",
    category: "activite",
    emoji: "🎩",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Cirque",
    category: "activite",
    emoji: "🎪",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Opéra",
    category: "activite",
    emoji: "🎭",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Ballet",
    category: "activite",
    emoji: "🩰",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Comédie musicale",
    category: "activite",
    emoji: "🎵",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Stand-up comedy",
    category: "activite",
    emoji: "😂",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Café-théâtre",
    category: "activite",
    emoji: "☕",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Improvisation théâtrale",
    category: "activite",
    emoji: "🎭",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Lecture publique",
    category: "activite",
    emoji: "📖",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Conférence",
    category: "activite",
    emoji: "🎤",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
  {
    label: "Atelier créatif",
    category: "activite",
    emoji: "🎨",
    weight: 1,
    actions: ["maps"],
    isDefault: true,
    isActive: true,
  },
];

const CONFIG_DEFAULTS: ConfigDefaults = {
  FREE_ROLLS_PER_DAY: 3,
  LIFETIME_PRICE: "5,99 €",
  PAYWALL_TITLE: "Accès à vie 💕",
  PAYWALL_BULLETS: "Lancers illimités|Dés personnalisables|Aucune pub",
  FEATURE_FLAGS: {
    customFaces: true,
    history: true,
    analytics: true,
    sharing: true,
  },
};

async function initializeFirebase(): Promise<FirebaseContext> {
  const app = initializeApp(firebaseConfig);
  const db = getFirestore(app);
  const auth = getAuth(app);
  await signInAnonymously(auth);
  return { app, db, auth };
}

async function migrateDefaultFaces(db: Firestore): Promise<void> {
  const defaultFacesRef = collection(db, "defaultFaces");
  const batch = writeBatch(db);

  DEFAULT_FACES.forEach((face, index) => {
    const faceRef = doc(defaultFacesRef, `default_${index}`);
    batch.set(faceRef, {
      ...face,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });
  });

  await batch.commit();
  console.log(`✅ Migrated ${DEFAULT_FACES.length} default faces`);
}

async function initializeAppConfig(db: Firestore): Promise<void> {
  const configRef = doc(db, "appConfig", "main");
  await setDoc(configRef, {
    ...CONFIG_DEFAULTS,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
  console.log("✅ Initialized app config");
}

async function initializeRemoteConfig(db: Firestore): Promise<void> {
  const configRef = collection(db, "remoteConfig");
  const batch = writeBatch(db);

  Object.entries(CONFIG_DEFAULTS).forEach(([key, value]) => {
    const configDocRef = doc(configRef, key);
    batch.set(configDocRef, {
      value,
      type: typeof value === "object" ? "json" : typeof value,
      createdAt: serverTimestamp(),
    });
  });

  await batch.commit();
  console.log("✅ Initialized remote config");
}

async function createSampleUserData(db: Firestore, auth: Auth): Promise<void> {
  const user = auth.currentUser;
  if (!user) return;

  const userRef = doc(db, "users", user.uid);
  await setDoc(userRef, {
    createdAt: serverTimestamp(),
    hasLifetime: false,
    freeRollsUsedToday: 0,
    freeDayKey: new Date().toISOString().split("T")[0],
    prefs: {
      haptics: true,
      weights: { payer: 0.2, repas: 0.2, activite: 0.6 },
    },
    notificationsEnabled: false,
    notificationPreferences: {
      enabled: true,
      eveningReminders: true,
      milestoneAlerts: true,
      weeklyDigest: false,
      marketingEmails: false,
      reminderTime: "19:00",
    },
    lastSyncAt: serverTimestamp(),
  });
  console.log("✅ Created sample user data");
}

async function checkFirestoreRules(): Promise<void> {
  console.log("📋 Firestore rules should be deployed separately");
  console.log("   Rules will be deployed via firebase deploy --only firestore:rules");
}

async function createStatistics(db: Firestore): Promise<void> {
  const statsRef = doc(db, "stats", "global");
  await setDoc(statsRef, {
    totalUsers: 0,
    totalRolls: 0,
    totalLifetimePurchases: 0,
    dailyActiveUsers: 0,
    monthlyActiveUsers: 0,
    lastUpdated: serverTimestamp(),
    createdAt: serverTimestamp(),
  });
  console.log("✅ Created global statistics");
}

async function createFirestoreIndexes(): Promise<void> {
  console.log("📋 Firestore indexes should be created via firebase deploy --only firestore:indexes");
  console.log("   Using the firestore.indexes.json file in the project root");
  console.log("   Indexes will be automatically created when you deploy to Firebase");
}

async function createCategoriesStats(db: Firestore): Promise<void> {
  const stats = {
    payer: DEFAULT_FACES.filter(face => face.category === "payer").length,
    repas: DEFAULT_FACES.filter(face => face.category === "repas").length,
    activite: DEFAULT_FACES.filter(face => face.category === "activite").length,
  };

  const categoryStatsRef = doc(db, "stats", "categories");
  await setDoc(categoryStatsRef, {
    ...stats,
    total: stats.payer + stats.repas + stats.activite,
    createdAt: serverTimestamp(),
  });
  console.log(`✅ Created category statistics - Payer: ${stats.payer}, Repas: ${stats.repas}, Activité: ${stats.activite}`);
}

async function runMigration(): Promise<void> {
  try {
    console.log("🚀 Starting Firebase migration...");
    const { db, auth } = await initializeFirebase();
    console.log("✅ Firebase initialized");
    
    await migrateDefaultFaces(db);
    await initializeAppConfig(db);
    await initializeRemoteConfig(db);
    await createStatistics(db);
    await createCategoriesStats(db);
    await createFirestoreIndexes();
    await createSampleUserData(db, auth);
    await checkFirestoreRules();
    
    console.log("🎉 Migration completed successfully!");
    console.log(`📊 Total faces migrated: ${DEFAULT_FACES.length}`);
  } catch (error) {
    console.error("❌ Migration failed:", error);
    process.exit(1);
  }
}

// Point d'entrée du script
if (require.main === module) {
  runMigration();
}

export { CONFIG_DEFAULTS, DEFAULT_FACES, runMigration };
export type { ConfigDefaults, DiceFace, FirebaseContext };